src/LibrarySystemAdrienne.Web.Mvc/Models/Borrowers/BorrowerListViewModel.cs
using LibrarySystemAdrienne.Borrowers.Dto;
using System.Collections.Generic;

namespace LibrarySystemAdrienne.Web.Models.Borrowers
{
    public class BorrowerListViewModel
    {
        public List<BorrowerDto> Borrowers { get; set; }
    }
}

src/LibrarySystemAdrienne.Web.Mvc/Models/Borrowers/CreateOrEditBorrowerViewModel.cs
using LibrarySystemAdrienne.Books.Dto;
using LibrarySystemAdrienne.Borrowers.Dto;
using LibrarySystemAdrienne.Entities;
using LibrarySystemAdrienne.Students.Dto;
using System;
using System.Collections.Generic;

namespace LibrarySystemAdrienne.Web.Models.Borrowers
{
    public class CreateOrEditBorrowerViewModel
    {
        public int Id { get; set; }

        public DateTime BorrowDate { get; set; }

        public DateTime ExpectedReturnDate { get; set; }

        public DateTime ReturnDate { get; set; }

        public int BookId { get; set; }

        public int StudentId { get; set; }

        public List<BookDto> Books { get; set; }

        public List<StudentDto> Students { get; set; }



    }
}

src/LibrarySystemAdrienne.Web.Mvc/Controllers/BorrowersController.cs
using LibrarySystemAdrienne.Books;
using LibrarySystemAdrienne.Borrowers;
using LibrarySystemAdrienne.Borrowers.Dto;
using LibrarySystemAdrienne.Controllers;
using LibrarySystemAdrienne.Students;
using LibrarySystemAdrienne.Web.Models.Borrowers;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace LibrarySystemAdrienne.Web.Controllers
{
    public class BorrowersController : LibrarySystemAdrienneControllerBase
    {

        private IBorrowerAppService _borrowerIAppService;
        private IBookAppService _bookIAppService;
        private IStudentAppService _studentIAppService;

        public BorrowersController(IBorrowerAppService borrowerIAppService, IBookAppService bookIAppService, IStudentAppService studentIAppService)
        {
            _borrowerIAppService = borrowerIAppService;
            _bookIAppService = bookIAppService;
            _studentIAppService = studentIAppService;
        }

        #region Borrower Index Page View
        public async Task<IActionResult> Index(string searchBorrower)
        {
            var borrowers = await _borrowerIAppService.GetAllBorrowerWithStudentAndBook(new PagedBorrowerResultRequestDto { MaxResultCount = int.MaxValue });

            var model = new BorrowerListViewModel();

            if (searchBorrower != null)
            {
                model = new BorrowerListViewModel()
                {
                    Borrowers = borrowers.Items.Where(input => 
                    input.ReturnDate!.ToString().Contains(searchBorrower) || 
                    input.Book.BookTitle.ToString().Contains(searchBorrower) || 
                    input.Student.StudentName.ToString().Contains(searchBorrower) ||
                    input.Id!.ToString().Contains(searchBorrower) ||
                    input.ExpectedReturnDate.ToString().Contains(searchBorrower)).ToList(),
                };
            }
            else
            {
                model = new BorrowerListViewModel()
                {
                    Borrowers = borrowers.Items.ToList(),
                };
            }

            return View(model);
        }
        [HttpGet]
        #endregion

        #region Borrowers Create Page View
        public async Task<IActionResult> CreateBorrowers()
        {
            var model = new CreateOrEditBorrowerViewModel();
            var book = await _bookIAppService.GetAllBooksToBeBorrowed();
            var student = await _studentIAppService.GetAllBorrowersStudent();

            model.Books = book;
            model.Students = student;

            return View(model);
        }
        #endregion


        #region Borrowers Return Page View
        public async Task<IActionResult> UpdateBorrowers(int id)
        {
            var model = new CreateOrEditBorrowerViewModel();
            var book = await _bookIAppService.GetAllBooksToBeBorrowed(); 
            var student = await _studentIAppService.GetAllBorrowersStudent();

            if (id != 0)
            {
                var borrowers = await _borrowerIAppService.GetBorrowerWithBook(id);
                model = new CreateOrEditBorrowerViewModel()
                {
                    Id = borrowers.Id,
                    BorrowDate = borrowers.BorrowDate,
                    ExpectedReturnDate = borrowers.ExpectedReturnDate,
                    ReturnDate = borrowers.ReturnDate,
                    BookId = borrowers.BookId,
                    StudentId = borrowers.StudentId,
                };

                book.Add(borrowers.Book);
            }

            model.Books = book;
            model.Students = student;

            return View(model);
        }
        #endregion

        #region Borrowers Edit Page View
        public async Task<IActionResult> EditBorrowers(int id)
        {
            var model = new CreateOrEditBorrowerViewModel();
            var book = await _bookIAppService.GetAllBooksToBeBorrowed();
            var student = await _studentIAppService.GetAllBorrowersStudent();

            if (id != 0)
            {
                var borrowers = await _borrowerIAppService.GetBorrowerWithBook(id);
                model = new CreateOrEditBorrowerViewModel()
                {
                    Id = borrowers.Id,
                    BorrowDate = borrowers.BorrowDate,
                    ExpectedReturnDate = borrowers.ExpectedReturnDate,
                    BookId = borrowers.BookId,
                    StudentId = borrowers.StudentId,
                };

                book.Add(borrowers.Book);
            }

            model.Books = book;
            model.Students = student;

            return View(model);
        }
        #endregion
    }
}

src/LibrarySystemAdrienne.Web.Mvc/Views/Borrowers/CreateBorrowers.cshtml
@*
    For Borrowers > Create
*@

@using LibrarySystemAdrienne.Web.Models.Borrowers
@using LibrarySystemAdrienne.Web.Startup
@using LibrarySystemAdrienne.Web.Controllers

@model CreateOrEditBorrowerViewModel


@{
    ViewBag.Title = L("AddBorrower");
    ViewBag.CurrentPageName = PageNames.Borrowers;
}

@section scripts{
    <environment names="Development">
        <script src="~/view-resources/Views/Borrowers/CreateBorrower.js" asp-append-version="true"></script>
    </environment>
}

<form name="CreateBorrowerForm" id="CreateBorrowerForm" role="form" class="form-horizontal">

    <div class="modal-body" style="">

        <label style="font-size:24px" class="col-md-3 col-form-label">Add Borrower</label>

        <input type="hidden" name="Id" value="@Model?.Id" data-borrower-id />

        <div class="form-group row required">
            <div class="col-12">
                <div style="display:flex; justify-content:center;align-items:center;" class="row">

                    <div class="col-md-6 form-group">

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="BorrowDate">Date Borrowed</label>
                            <input id="BorrowDate" type="date" name="BorrowDate" value="@Model?.BorrowDate" placeholder="Pick Borrowed Date" class="form-control" data-borrowed-date required>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-4 col-form-label" for="ExpectedReturnDate">Expected Return Date</label>
                            <input id="ExpectedReturnDate" type="date" name="ExpectedReturnDate" value="@Model?.ExpectedReturnDate" placeholder="Pick Expected Return" class="form-control" data-expected-return-date required>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Books">Select Book</label>
                            @Html.DropDownListFor(m => m.BookId, Model.Books.Select(d => new SelectListItem {Text = d.BookTitle, Value = d.Id.ToString()}),"Select Book", new {@class = "form-control"})
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Students">Select Student</label>
                            @Html.DropDownListFor(m => m.StudentId, Model.Students.Select(d => new SelectListItem {Text = d.StudentName, Value = d.Id.ToString()}),"Select Student", new {@class = "form-control"})
                        </div>

                        <input type="hidden" name="IsBorrowed" id="IsBorrowed" value="true" data-IsBorrowed />


                    </div>
                </div>

                <div style="display:flex; justify-content:center;align-items:center;" class="row">
                    <button style="width:70px; height:40px; margin:5px;" id="Submit" type="submit" name="Submit" class="btn bg-blue float-sm-right save-button"> @L("Save") </button>
                    <button style="width:70px; height:40px; margin:5px;" id="Cancel" type="button" name="Cancel" class="btn btn-sm bg-secondary cancel-button"> @L("Cancel") </button>
                </div>
            </div>


        </div>
    </div>
</form>

src/LibrarySystemAdrienne.Web.Mvc/Views/Borrowers/EditBorrowers.cshtml
@*
    For Borrowers > Edit
*@

@using LibrarySystemAdrienne.Web.Models.Borrowers
@using LibrarySystemAdrienne.Web.Controllers
@using LibrarySystemAdrienne.Web.Startup

@model CreateOrEditBorrowerViewModel

@{
    ViewBag.Title = L("Edit");
    ViewBag.CurrentPageName = PageNames.Borrowers;
}


@section scripts{
    <environment names="Development">
        <script src="~/view-resources/Views/Borrowers/UpdateBorrowers.js" asp-append-version="true"></script>
    </environment>
}

<form name="EditForm" id="EditForm" role="form" class="form-horizontal">

    <div class="modal-body" style="">

        <label style="font-size:24px" class="col-md-3 col-form-label">Edit </label>

        <input type="hidden" name="Id" value="@Model?.Id" data-borrower-id />

        <div class="form-group row required">
            <div class="col-12">
                <div style="display:flex; justify-content:center;align-items:center;" class="row">

                    <div class="col-md-6 form-group">

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="BorrowDate">Date Borrowed</label>
                            <input id="BorrowDate" type="date" disabled name="BorrowDate" value="@Model?.BorrowDate" placeholder="Pick Borrowed Date" class="form-control" data-borrowed-date>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-4 col-form-label" for="ExpectedReturnDate">Expected Return Date</label>
                            <input id="ExpectedReturnDate" type="date" name="ExpectedReturnDate" value="@Model?.ExpectedReturnDate" placeholder="Pick Expected Return" class="form-control" data-expected-return-date>
                        </div>

                        <div hidden class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Name">Select Book</label>
                            @Html.DropDownListFor(m => m.BookId, Model.Books.Select(d => new SelectListItem {Text = d.BookTitle, Value = d.Id.ToString()}),"Select Book", new {@class = "form-control" })
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Name">Select Student</label>
                            @Html.DropDownListFor(m => m.StudentId, Model.Students.Select(d => new SelectListItem {Text = d.StudentName, Value = d.Id.ToString()}),"Select Student", new {@class = "form-control" })
                        </div>

                        <input type="hidden" name="IsBorrowed" id="IsBorrowed" value="true" data-isBorrowed />

                    </div>
                </div>

                <div style="display:flex; justify-content:center;align-items:center;" class="row">
                    <button style="width:70px; height:40px; margin:5px;" id="Submit" type="submit" name="Submit" class="btn bg-blue float-sm-right save-button"> @L("Save") </button>
                    <button style="width:70px; height:40px; margin:5px;" id="Cancel" type="button" name="Cancel" class="btn btn-sm bg-secondary cancel-button"> @L("Cancel") </button>
                </div>
            </div>


        </div>
    </div>
</form>

src/LibrarySystemAdrienne.Web.Mvc/Views/Borrowers/Index.cshtml
@*
    For Borrowers > Index
*@

@using LibrarySystemAdrienne.Web.Models.Borrowers
@using LibrarySystemAdrienne.Web.Controllers
@using LibrarySystemAdrienne.Web.Startup

@model BorrowerListViewModel

@{
    ViewBag.Title = L("Borrower");
    ViewBag.CurrentPageName = PageNames.Borrowers;
}


@section scripts{
    <environment names="Development">
        <script src="~/view-resources/Views/Borrowers/Index.js" asp-append-version="true"></script>
    </environment>
}

<section class="content-header">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h1>@L("Borrower")</h1>
            </div>
            <div class="col-sm-6">
            </div>
        </div>
    </div>

</section>

<section class="content">

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card">

                    <div class="card-header">

                        <a class="btn bg-blue float-sm-right" asp-controller="Borrowers" asp-action="CreateBorrowers">
                            <i class="fa fa-plus-square"></i>
                            @L("AddBorrower")
                        </a>

                        <div class="col-sm-6">
                        </div>

                        <div class="row">

                            <form asp-controller="Borrowers" asp-action="Index" method="get">

                                <div class="input-group">

                                    <input type="text" name="searchBorrower" class="form-control txt-search" />

                                    <div class="input-group-prepend">

                                        <button type="submit" name="searchBorrower" class="btn bg-blue btn-search">
                                            <span class="fas fa-search" aria-hidden="true"></span>@L("Search")
                                        </button>

                                    </div>

                                </div>
                            </form>
                        </div>

                        <div class="col-md-6">
                        </div>

                    </div>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="BorrowerTable" class="table table-striped table-bordered">
                            <thead>
                                <tr>

                                    <th>@L("BorrowerID")</th>
                                    <th>@L("Borrower")</th>
                                    <th>@L("BookName")</th>
                                    <th>@L("BorrowDate")</th>
                                    <th>@L("ExpectedReturnDate")</th>
                                    <th>@L("ReturnDate")</th>
                                    

                                    <th style="width: 150px">@L("Actions")</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var borrower in Model.Borrowers)
                                {      
                                    
                                    @if (borrower.ExpectedReturnDate < borrower.ReturnDate)
                                    {           <!--  Book Returned Late  -->

                                        <tr style="background-color:firebrick" id="borrowerTable">

                                            <td>@borrower.Id</td>
                                            <td>@borrower.Student?.StudentName</td>
                                            <td>@borrower.Book?.BookTitle</td>
                                            <td>@borrower.BorrowDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.ExpectedReturnDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.ReturnDate.ToString("MMMM/dd/yyyy")</td>

                                            <td>

                                                <button disabled style="width:100px; height:50px;" type="button" class="btn btn-sm bg-danger btn-return">
                                                    Late @*fas fa-hand-holding*@
                                                </button>

                                            </td>
                                        </tr>
                                    }
                                    else if (borrower.BorrowDate > borrower.ReturnDate)
                                    {            <!-- To be return -->
                                        
                                        <tr id="borrowerTable">

                                            <td>@borrower.Id</td>
                                            <td>@borrower.Student?.StudentName</td>
                                            <td>@borrower.Book?.BookTitle</td>
                                            <td>@borrower.BorrowDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.ExpectedReturnDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.Book?.IsBorrowed</td>
                                                           

                                            <td>
                                                <button style="width:60px; height:50px;" type="button" class="btn btn-sm bg-green btn-return" data-borrower-id="@borrower.Id">
                                                    @L("ReturnBook") @*fas fa-hand-holding*@
                                                </button>

                                                <button style="width:60px; height:50px;" type="button" class="btn btn-sm bg-danger delete-borrower" data-borrower-id="@borrower.Id" data-borrower-name="@borrower.Student.StudentName" data-book-id="@borrower.Book?.Id" data-book-name="@borrower.Book?.BookTitle" data-IsBorrowed="@borrower.Book?.IsBorrowed">
                                                    <i class="fas fa-trash"></i>
                                                </button>

                                                <button style="width:60px; height:50px;" type="button" class="btn btn-sm bg-secondary btn-edit" data-borrower-id="@borrower.Id" >
                                                    <i class="fas fa-pencil-alt"></i> @L("Edit")
                                                </button>

                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        <!--  Book Return on time -->

                                        <tr id="borrowerTable" style="background-color:lightgreen;">

                                            <td>@borrower.Id</td>
                                            <td>@borrower.Student?.StudentName</td>
                                            <td>@borrower.Book?.BookTitle</td>
                                            <td>@borrower.BorrowDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.ExpectedReturnDate.ToString("MMMM/dd/yyyy")</td>
                                            <td>@borrower.ReturnDate.ToString("MMMM/dd/yyyy")</td>

                                            <td>

                                                <button disabled style="width:100px; height:50px;" type="button" class="btn btn-sm bg-green btn-return" >
                                                    On Time @*fas fa-hand-holding*@
                                                </button>

                                                
                                            </td>
                                        </tr>
                                    }

                                }
                            </tbody>
                        </table>

                    </div>
                </div>


            </div>
        </div>
    </div>

</section>

src/LibrarySystemAdrienne.Web.Mvc/Views/Borrowers/UpdateBorrowers.cshtml
@*
    For Borrowers > Update
*@

@using LibrarySystemAdrienne.Web.Models.Borrowers
@using LibrarySystemAdrienne.Web.Controllers
@using LibrarySystemAdrienne.Web.Startup

@model CreateOrEditBorrowerViewModel

@{
    ViewBag.Title = L("ReturnBookBorrowed");
    ViewBag.CurrentPageName = PageNames.Borrowers;
}


@section scripts{
    <environment names="Development">
        <script src="~/view-resources/Views/Borrowers/UpdateBorrowers.js" asp-append-version="true"></script>
    </environment>
}

<form name="UpdateForm" id="UpdateForm" role="form" class="form-horizontal">

    <div class="modal-body" style="">

        <label style="font-size:24px" class="col-md-3 col-form-label">Return </label>

        <input type="hidden" name="Id" value="@Model?.Id" data-borrower-id />

        <div class="form-group row required">
            <div class="col-12">
                <div style="display:flex; justify-content:center;align-items:center;" class="row">

                    <div class="col-md-6 form-group">

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="BorrowDate">Date Borrowed</label>
                            <input id="BorrowDate" disabled type="date" name="BorrowDate" value="@Model?.BorrowDate" placeholder="Pick Borrowed Date" class="form-control" data-borrowed-date>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-4 col-form-label" for="ExpectedReturnDate">Expected Return Date</label>
                            <input id="ExpectedReturnDate" disabled type="date" name="ExpectedReturnDate" value="@Model?.ExpectedReturnDate" placeholder="Pick Expected Return" class="form-control" data-expected-return-date>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="ReturnDate">Returned Date</label>
                            <input id="ReturnDate" type="date" name="ReturnDate" value="@Model?.ReturnDate" class="form-control" data-return-date>
                        </div>

                        <div hidden class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Name">Select Book</label>
                            @Html.DropDownListFor(m => m.BookId, Model.Books.Select(d => new SelectListItem {Text = d.BookTitle, Value = d.Id.ToString()}),"Select Book", new {@class = "form-control" })
                        </div>

                        <div hidden class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Name">Select Student</label>
                            @Html.DropDownListFor(m => m.StudentId, Model.Students.Select(d => new SelectListItem {Text = d.StudentName, Value = d.Id.ToString()}),"Select Student", new {@class = "form-control" })
                        </div>

                        <input type="hidden" name="IsBorrowed" id="IsBorrowed" value="true" data-isBorrowed />

                    </div>
                </div>

                <div style="display:flex; justify-content:center;align-items:center;" class="row">
                    <button style="width:70px; height:40px; margin:5px;" id="Submit" type="submit" name="Submit" class="btn bg-blue float-sm-right save-button"> @L("Save") </button>
                    <button style="width:70px; height:40px; margin:5px;" id="Cancel" type="button" name="Cancel" class="btn btn-sm bg-secondary cancel-button"> @L("Cancel") </button>
                </div>
            </div>


        </div>
    </div>
</form>