src/LibrarySystemAdrienne.Web.Mvc/Models/BookCategories/CreateOrEditBookCategoryViewModel.cs
using LibrarySystemAdrienne.Departments.Dto;
using LibrarySystemAdrienne.Entities;
using System.Collections.Generic;

namespace LibrarySystemAdrienne.Web.Models.BookCategories
{
    public class CreateOrEditBookCategoryViewModel
    {

        public int Id { get; set; }

        public string CategoryName { get; set; }

        public int DepartmentId { get; set; }

        public List<DepartmentDto> Departments { get; set; }

    }
}

src/LibrarySystemAdrienne.Web.Mvc/Controllers/BooksCategoriesController.cs
using Abp.Application.Services.Dto;
using LibrarySystemAdrienne.BookCategory;
using LibrarySystemAdrienne.BookCategory.Dto;
using LibrarySystemAdrienne.Controllers;
using LibrarySystemAdrienne.Departments;
using LibrarySystemAdrienne.Web.Models.BookCategories;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace LibrarySystemAdrienne.Web.Controllers
{
    public class BooksCategoriesController : LibrarySystemAdrienneControllerBase
    {
        private IBookCategoryAppService _categoryIAppService;
        private IDepartmentAppService _departmentIAppService;

        public BooksCategoriesController(IBookCategoryAppService categoryIAppService, IDepartmentAppService departmentIAppService)
        {
            _categoryIAppService = categoryIAppService;
            _departmentIAppService = departmentIAppService;
        }

        #region Category Index Page View
        public async Task<IActionResult> Index(string searchCategory)
        {
            var category = await _categoryIAppService.GetAllBookCategoryWithDepartment(new PagedBookCategoryResultRequestDto { MaxResultCount = int.MaxValue });

            var model = new BookCategoryListViewModel();

            if (searchCategory != null)
            {
                model = new BookCategoryListViewModel()
                {
                    BookCategories = category.Items.Where(input =>
                    input.Id!.ToString().Contains(searchCategory) ||
                    input.Department.DepartmentName!.ToString().Contains(searchCategory) ||
                    input.CategoryName!.Contains(searchCategory)).ToList(),
                };
            }
            else
            {
                model = new BookCategoryListViewModel()
                {
                    BookCategories = category.Items.ToList(),
                };
            }

            return View(model);


        }
        [HttpGet]
        #endregion

        #region Category Create or Edit Page View
        public async Task<IActionResult> CreateOrEditBookCategory(int id)
        {
            var model = new CreateOrEditBookCategoryViewModel();
            var departments = await _departmentIAppService.GetAllDepartments(); //galing sa app service to end point here at controller 

            if (id != 0)
            {
                var category = await _categoryIAppService.GetAsync(new EntityDto<int>(id));

                model = new CreateOrEditBookCategoryViewModel()
                {
                    Id = category.Id,
                    CategoryName = category.CategoryName,
                    DepartmentId = category.DepartmentId,
                };
            }

            model.Departments = departments;

            return View(model);
        }
        #endregion

    }
}

src/LibrarySystemAdrienne.Web.Mvc/Views/BooksCategories/CreateOrEditBookCategory.cshtml
@*
    For Book Category > Create or Edit
*@

@using LibrarySystemAdrienne.Web.Models.BookCategories
@using LibrarySystemAdrienne.Web.Controllers
@using LibrarySystemAdrienne.Web.Startup

@model CreateOrEditBookCategoryViewModel

@{
    ViewBag.Title = L("CreateOrEdit");
    ViewBag.CurrentPageName = PageNames.BookCategories;
}

@section scripts{
    <environment names="Development">
        <script src="~/view-resources/Views/BookCategories/CreateOrEditBookCategory.js" asp-append-version="true"></script>
    </environment>
}

<form name="CreateBookCategoryForm" id="CreateBookCategoryForm" role="form" class="form-horizontal">

    <div class="modal-body" style="">

        <label style="font-size:24px" class="col-md-3 col-form-label">Category</label>

        <input type="hidden" name="Id" value="@Model?.Id" data-category-name />

        <div class="form-group row required">
            <div class="col-12">
                <div style="display:flex; justify-content:center;align-items:center;" class="row">

                    <div class="col-md-6 form-group">

                        <div class="form-group row required">
                            <label class="col-md-4 col-form-label" for="Name">Category</label>
                            <input id="CategoryName" type="text" name="CategoryName" value="@Model?.CategoryName" placeholder="Enter Category Name" class="form-control" data-category-Name required>
                        </div>

                        <div class="form-group row required">
                            <label class="col-md-3 col-form-label" for="Name">Department</label>
                            @Html.DropDownListFor(m => m.DepartmentId, Model.Departments.Select(d => new SelectListItem {Text = d.DepartmentName, Value = d.Id.ToString()}),"Select Department", new {@class = "form-control"})
                        </div>

                    </div>

                </div>

                <div style="display:flex; justify-content:center;align-items:center;" class="row">
                    <button style="width:70px; height:40px; margin:5px;" id="Submit" type="submit" name="Submit" class="btn bg-blue float-sm-right save-button"> @L("Save") </button>
                    <button style="width:70px; height:40px; margin:5px;" id="Cancel" type="button" name="Cancel" class="btn btn-sm bg-secondary cancel-button">@L("Cancel")</button>
                </div>
            </div>


        </div>
    </div>
</form>

src/LibrarySystemAdrienne.Web.Mvc/Views/BooksCategories/Index.cshtml
@*
    For Book Category > Index
*@

@using LibrarySystemAdrienne.Web.Models.BookCategories
@using LibrarySystemAdrienne.Web.Controllers
@using LibrarySystemAdrienne.Web.Startup

@model BookCategoryListViewModel

@{
    ViewBag.Title = L("Category");
    ViewBag.CurrentPageName = PageNames.BookCategories;
}

@section scripts{

    <environment names="Development">
        <script src="~/view-resources/Views/BookCategories/Index.js" asp-append-version="true"></script>
    </environment>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h1>@L("Category")</h1>
            </div>
            <div class="col-sm-6">
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card">

                    <div class="card-header">

                        <a class="btn bg-blue float-sm-right" asp-controller="BooksCategories" asp-action="CreateOrEditBookCategory">
                            <i class="fa fa-plus-square"></i>
                            @L("AddCategory")
                        </a>

                        <div class="col-sm-6">
                        </div>

                        <div class="row">

                            <div class="col-md-6">

                                <form asp-controller="BooksCategories" asp-action="Index" method="get">

                                    <div class="input-group">

                                        <input type="text" name="searchCategory" class="form-control txt-search" />

                                        <div class="input-group-prepend">

                                            <button type="submit" name="searchCategory" class="btn bg-blue btn-search">
                                                <span class="fas fa-search" aria-hidden="true"></span>@L("Search")
                                            </button>

                                        </div>

                                    </div>
                                </form>

                            </div>

                            <div class="col-md-6">
                            </div>

                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="CategoryTable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>@L("CategoryId")</th>
                                        <th>@L("CategoryName")</th>
                                        <th>@L("Departments")</th>

                                        <th style="width: 150px">@L("Actions")</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var category in Model.BookCategories)
                                    {
                                        <tr>
                                            <td>@category.Id</td>
                                            <td>@category.CategoryName</td>
                                            <td>@category.Department?.DepartmentName</td>

                                            <td>
                                                <button style="width:60px; height:30px;" type="button" class="btn btn-sm bg-secondary edit-category" data-category-id="@category.Id">
                                                    <i class="fas fa-pencil-alt"></i> @L("Edit")
                                                </button>
                                                <button style="width:60px; height:30px;" type="button" class="btn btn-sm bg-danger delete-category" data-category-id="@category.Id" data-category-name="@category.CategoryName">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>